### ISSUE TITLE
Auto Rename Recordings

### ISSUE THREAD

**Issue by mazac44** [gafirst/match-uploader#70]
Using the match start and stop times from the TBA API, rename the video files that are recorded from vMix and then upload the video so that they do not need to be manually renamed.

**Comment by evan10s** [comment]
Spec

* new worker job that triggers every 5 minutes  
  * check for files that match the un-renamed match regex  
  * get match data from TBA  
  * get event data from TBA if not saved  
  * if there are unrenamed files, then for each file sorted by ascending timestamp  
    * check the DB VideoFileMatch table to see if we've tried matching this file previously  
    * stop if the association status is not unmatched  
    * attempt to find a match for the video (see algorithm below)  
    * if a match is found+confident:  
      * set VideoFileMatch to approved, rename video file  
      * record as the highest found match for this label \+ event  
      * if a match is found \+ not confident:  
        * set VideoFileMatch to pending, send webhook event for UI  
    * if a match is not found:  
      * create VideoFileMatch for file if it doesn't exist  
      * increment association\_attempts  
      * set status to FAILED if max attempts exceeded, send webhook event to UI  
    * if matching algorithm errored:  
      * not found handling but set status to FAILED if the error is unrecoverable

video file matching algorithm:

* input: filename, parsed date, label  
* if the date is invalid or not within the event start/end time for this event key \+ label, return this as an unrecoverable error  
* create a variable to store the closest match start timestamp  
* for each match in the TBA match data, ordered by ascending match key  
  * if |filename time \- match start time| \< saved value, store as new closest match  
  * if we find a match where the improvement on closest time is \< 4 minutes (based on match cycle time, this is sus), return a nonrecoverable error  
* if no closest match is found:  
  * return the error  
* if the closest match is too far off (more than 1-2 minutes maybe)  
  * return as matched \+ non-confident if the error is \< 15 mins  
* otherwise return as no match with the error that the closest match was too far off  
* if the closest match is behind the last associated match for this label or skipping ahead by more than 2 matches  
  * return as matched \+ non-confident  
* otherwise, we should have a confident association. return matched \+ confident  
  * (optional) if a settings flag is set or we haven't completed 5 associations for the current day, return matched \+ non-confident for human validation

in the UI, there will be a new page to handle human review of match associations

* the primary view will show non-confident associations as well as errored assocations  
  * it'll be possible to authoritatively fix these as a human  
* it will probably also show past confident associations and allow clearing them if they're wrong  
* it will show the current live mode status with a button to pause live mode  
* it might have a way to grab screenshots from \~40 seconds into the view to allow quickly confirming the match association is correct
